// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// admm
arma::colvec admm(arma::mat Dmat, arma::mat dvec, arma::mat Amat, arma::mat bvec, arma::mat lb, arma::mat ub);
RcppExport SEXP _syntheticRcpp_admm(SEXP DmatSEXP, SEXP dvecSEXP, SEXP AmatSEXP, SEXP bvecSEXP, SEXP lbSEXP, SEXP ubSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Dmat(DmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dvec(dvecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bvec(bvecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ub(ubSEXP);
    rcpp_result_gen = Rcpp::wrap(admm(Dmat, dvec, Amat, bvec, lb, ub));
    return rcpp_result_gen;
END_RCPP
}
// fn_v
double fn_v(Rcpp::NumericVector& v_vec, arma::mat x0_scaled, arma::mat x1_scaled, arma::mat z0, arma::mat z1);
RcppExport SEXP _syntheticRcpp_fn_v(SEXP v_vecSEXP, SEXP x0_scaledSEXP, SEXP x1_scaledSEXP, SEXP z0SEXP, SEXP z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type v_vec(v_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x0_scaled(x0_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x1_scaled(x1_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z1(z1SEXP);
    rcpp_result_gen = Rcpp::wrap(fn_v(v_vec, x0_scaled, x1_scaled, z0, z1));
    return rcpp_result_gen;
END_RCPP
}
// inference
arma::mat inference(arma::mat& y0, arma::mat& y1, arma::mat& x0_scaled, arma::mat& x1_scaled, arma::mat& z0, arma::mat& z1);
RcppExport SEXP _syntheticRcpp_inference(SEXP y0SEXP, SEXP y1SEXP, SEXP x0_scaledSEXP, SEXP x1_scaledSEXP, SEXP z0SEXP, SEXP z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x0_scaled(x0_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x1_scaled(x1_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type z1(z1SEXP);
    rcpp_result_gen = Rcpp::wrap(inference(y0, y1, x0_scaled, x1_scaled, z0, z1));
    return rcpp_result_gen;
END_RCPP
}
// synthetic
Rcpp::List synthetic(arma::mat& y0, arma::mat& y1, arma::mat& x0_scaled, arma::mat& x1_scaled, arma::mat& z0, arma::mat& z1);
RcppExport SEXP _syntheticRcpp_synthetic(SEXP y0SEXP, SEXP y1SEXP, SEXP x0_scaledSEXP, SEXP x1_scaledSEXP, SEXP z0SEXP, SEXP z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x0_scaled(x0_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x1_scaled(x1_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type z1(z1SEXP);
    rcpp_result_gen = Rcpp::wrap(synthetic(y0, y1, x0_scaled, x1_scaled, z0, z1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_syntheticRcpp_admm", (DL_FUNC) &_syntheticRcpp_admm, 6},
    {"_syntheticRcpp_fn_v", (DL_FUNC) &_syntheticRcpp_fn_v, 5},
    {"_syntheticRcpp_inference", (DL_FUNC) &_syntheticRcpp_inference, 6},
    {"_syntheticRcpp_synthetic", (DL_FUNC) &_syntheticRcpp_synthetic, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_syntheticRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
