# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' quadratic programming with linear equality and box inequality constraints using ADMM
#'@param Dmat : a size (n x n) matrix representing D matrix involved in the quadratic term x. Must be positive semi-definite.
#'@param dvec : a size n vector representing d involved in the linear term of x.
#'@param Amat : a size (m x n) matrix representing A matrix involved in the linear equality constraint of x. 
#'@param bvec : a size m vector representing b involved in the linear equality constraint.
#'@param lb   : a size n vector representing the lower bound of box-inequality constraint of x.
#'@param ub   : a size n vector representing the upper bound of box-inequality constraint of x.
#'@return : a vector containing x, where x is a size N_co vector containing optimal weights for control units.
#'@export
admm <- function(Dmat, dvec, Amat, bvec, lb, ub) {
    .Call('_syntheticRcpp_admm', PACKAGE = 'syntheticRcpp', Dmat, dvec, Amat, bvec, lb, ub)
}

#' quadratic programming with linear equality and box inequality constraints using ADMM
#'@param Dmat : a size (n x n) matrix representing D matrix involved in the quadratic term x. Must be positive semi-definite.
#'@param dvec : a size n vector representing d involved in the linear term of x.
#'@param Amat : a size (m x n) matrix representing A matrix involved in the linear equality constraint of x. 
#'@param bvec : a size m vector representing b involved in the linear equality constraint.
#'@param lb   : a size n vector representing the lower bound of box-inequality constraint of x.
#'@param ub   : a size n vector representing the upper bound of box-inequality constraint of x.
#'@return : a vector containing x, where x is a size N_co vector containing optimal weights for control units.
#'@export
NULL

#'This is the optimizing function (minimization) for V
#'
#'@param v_vec : a k-dim vector of initial values for V
#'@param x0_scaled : a (k x Nc) matrix of scaled predictors for control group during pre-treatment times
#'@param x1_scaled : a (k x 1) scaled predictors for treated group during pre-treatment times
#'@param z0 : a (T0 x Nc) matrix of outcomes for control group during pre-treatment times
#'@param z1 : a (T0 x 1)  matrix of outcomes for treated group during pre-treatment times
#'@return a scalar of V loss during pre-treatment times : t(X1-X0%*%W) %*% V %*% (X1-X0%*%W)
#'@export
fn_v <- function(v_vec, x0_scaled, x1_scaled, z0, z1) {
    .Call('_syntheticRcpp_fn_v', PACKAGE = 'syntheticRcpp', v_vec, x0_scaled, x1_scaled, z0, z1)
}

#'This is the optimizing function (minimization) for V
#'
#'@param v_vec : a k-dim vector of initial values for V
#'@param x0_scaled : a (k x Nc) matrix of scaled predictors for control group during pre-treatment times
#'@param x1_scaled : a (k x 1) scaled predictors for treated group during pre-treatment times
#'@param z0 : a (T0 x Nc) matrix of outcomes for control group during pre-treatment times
#'@param z1 : a (T0 x 1)  matrix of outcomes for treated group during pre-treatment times
#'@return a scalar of V loss during pre-treatment times : t(X1-X0%*%W) %*% V %*% (X1-X0%*%W)
#'@export
NULL

inference <- function(y0, y1, x0_scaled, x1_scaled, z0, z1) {
    .Call('_syntheticRcpp_inference', PACKAGE = 'syntheticRcpp', y0, y1, x0_scaled, x1_scaled, z0, z1)
}

#'This is the wrapping function of 1) estimation, 2) inference with parallel computing, and 3) graph
#'@param y0 : a (T x N_co) matrix of outcomes from control units
#'@param y1 : a (T-dim) vector of outcomes from treated units
#'@param x0_scaled : a (K x N_co) matrix of predictors for control units during pre-treatment times
#'@param x1_scaled : a K-dim vector of predictors for treated units during pre-treatment times
#'@param z0 : a (T0 x N_co) matrix of outcomes for control units during pre-treatment times
#'@param z1 : a (T0-dim) vector of outcomes for treated units during pre-treatment times
#'@return A list containing the following values
#' * ATT : (numeric) a T-dim vector of average treatment effect on treated across time (from the beginning to the end of study time)
#' * T_trajectory : (numeric) a T-dim vector of treatment group outcome trajectory across time
#' * SC_trajectory : (numeric) a T-dim vector of synthetic control outcome trajectory across time
#' * solution.v : (numeric) a (k x k) matrix of weight 
#' * solution.w : (numeric) a Nc-dim vector of synthetic weights for control units
#' @export
synthetic <- function(y0, y1, x0_scaled, x1_scaled, z0, z1) {
    .Call('_syntheticRcpp_synthetic', PACKAGE = 'syntheticRcpp', y0, y1, x0_scaled, x1_scaled, z0, z1)
}

#'This is the wrapping function of 1) estimation, 2) inference with parallel computing, and 3) graph
#'@param y0 : a (T x N_co) matrix of outcomes from control units
#'@param y1 : a (T-dim) vector of outcomes from treated units
#'@param x0_scaled : a (K x N_co) matrix of predictors for control units during pre-treatment times
#'@param x1_scaled : a K-dim vector of predictors for treated units during pre-treatment times
#'@param z0 : a (T0 x N_co) matrix of outcomes for control units during pre-treatment times
#'@param z1 : a (T0-dim) vector of outcomes for treated units during pre-treatment times
#'@return A list containing the following values
#' * ATT : (numeric) a T-dim vector of average treatment effect on treated across time (from the beginning to the end of study time)
#' * T_trajectory : (numeric) a T-dim vector of treatment group outcome trajectory across time
#' * SC_trajectory : (numeric) a T-dim vector of synthetic control outcome trajectory across time
#' * solution.v : (numeric) a (k x k) matrix of weight 
#' * solution.w : (numeric) a Nc-dim vector of synthetic weights for control units
#' @export
NULL

